### ISSUE TITLE
RPC data sending breaks for no apparent reason

### ISSUE THREAD

**Issue by Tenrys** [suclearnub/python-discord-rpc#1]
I'm making a CS:GO Discord Rich Presence add-on here: https://github.com/Tenrys/csgo_richpresence
And I've noticed that sometimes when switching teams in the game the RPC starts erroring like so:

![](https://tenrys.pw/ShareX/2018/Mar/z1wl.png)

I couldn't figure out why, it seems really weird that the flush function breaks.
Do you have any idea why this happens?
It first breaks on data like this:

![](https://tenrys.pw/ShareX/2018/Mar/1cwA.png)

Oddly enough, it doesn't happen on release 1.1.0 of my program, at least I don't think so, and I've made no apparent changes that look like it would break anything.

**Comment by the-emerald** [comment]
Will investigate. Stand by.

**Comment by the-emerald** [comment]
@Tenrys can I also see what "normal" data looks like? (i.e. without team switching). I'm still reading through your code, but my first instinct tells me it could be some sort of malformed data.

**Comment by Tenrys** [comment]
So you mean the raw data CS:GO gives out or the same data before the error?

**Comment by the-emerald** [comment]
The same data before the error / headers. I assume the RPC only breaks when sending a _new_ update that has a different team than the current one (a team switch)?

**Comment by Tenrys** [comment]
The only problem is that it doesn't `always` happen, sometimes I switch team and it works fine. Sometimes it errors immediately, some other times it takes some time before breaking. Right now I'm using a different library for my Discord IPC needs and it seems to be just fine, I guess I could go back to the previous version though to debug.

**Comment by the-emerald** [comment]
Could it be here? https://github.com/Tenrys/csgo_richpresence/commit/3ddcf37e6af29781ed0c79ba3c686deb266e4162

You're basically sending 2 activities if it works, sending one (and not catching the error) when the first one fails.

**Comment by Tenrys** [comment]
That was when I started having the bug, and I removed that `try` because it didn't help.

**Comment by the-emerald** [comment]
Mind if you do a `bisect` or tell me which commit introduced the bug? I think I know what it is.

**Comment by Tenrys** [comment]
That's the problem, I'm not sure what commit made it do this. Release 1.1.1 works fine, but anything after doesn't.
I'm guessing it could be this.. https://github.com/Tenrys/csgo_richpresence/commit/180a4a35c49d9bbc30dcabfbed9a8b8eccb00480
But nothing there should have introduced any issue.

**Comment by Tenrys** [comment]
I've got no idea how git bisect works.

**Comment by the-emerald** [comment]
`git bisect` is basically a binary search, it'll load a commit from the past, you test it and tell git whether that commit is `good` or `bad`, then it'll eventually tell you which commit introduced a bug.

Could it be this? https://github.com/Tenrys/csgo_richpresence/commit/180a4a35c49d9bbc30dcabfbed9a8b8eccb00480#diff-5bc02cefb3ea9e27f1a6776eabd1935dR26

Please try to see if the issue persists if you just make a new RPC object. There *shouldn't* be any reason that an RPC connection fails to establish, unless Discord isn't open. Perhaps you could catch that and just quit.

**Comment by Tenrys** [comment]
I tried reverting the rpc related change and it still happened, oddly enough.
