### ISSUE TITLE
Discord RP API documentation follows different field format

### ISSUE THREAD

**Issue by ben-dodd-dev** [suclearnub/python-discord-rpc#5]
More of a question than an issue. Why does your code follow a different data format for the activity fields than what is said on the Discord documentation?
For example:
`small_text` is under `assets` however on the Discord documentation they have it only as `smallImageText`

I'm unsure where I would put fields such as `partyId`, `partySize`, `joinSecret` etc.

Is it possible to use the Discord documentation field names rather than the ones that are currently in use? 
(My first issue I've opened so sorry if it's not up to par)

**Comment by the-emerald** [comment]
Sorry, but I haven't had the time to get around to fixing it. If you'd like to please send in a PR :)

**Comment by ben-dodd-dev** [comment]
Looked through some references, especially [Discord RPC Hard Mode](https://github.com/discordapp/discord-rpc/blob/master/documentation/hard-mode.md) and found the field names that correspond to those in the Discord Documentation. I might send a PR that converts the new field names to the ones that Discord RPC uses. 😄
